export const  cookies  = [
    {
        "domain": ".youtube.com",
        "expirationDate": 1743928479.86328,
        "hostOnly": false,
        "httpOnly": true,
        "name": "VISITOR_PRIVACY_METADATA",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "CgJQSxIEGgAgSg%3D%3D"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1733414518,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1.1.1105463588.1725638518"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1762402122.12545,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-YEC",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "CgtaeU1PcS1kbVVIcyjjvY24BjIKCgJHQhIEGgAgaA%3D%3D"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1764845011.278565,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "g.a000pgifhjfpgxS7CvT5PGgI1X8OePgRoYbEOYFJLaVgu3vR_tZVET46uE0X12I0_xBYEX_KRgACgYKAQwSARUSFQHGX2MiAQyPNqt64fgzJ6I4TRdJvhoVAUF8yKojCsbl_FV8v7YSsafqVlUa0076"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1761917069.770857,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "AKEyXzXAkwcdJmMZq_QiQ3aRnf7GXNrLKhJG0w3WR-PS-vI7MgudgcpUVjSxtlW8s4Ds9IxFqQ"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1764845011.278435,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "g.a000pgifhjfpgxS7CvT5PGgI1X8OePgRoYbEOYFJLaVgu3vR_tZV5MFQP-QNjvv2JY4ZOvJVGwACgYKAd8SARUSFQHGX2Mi-aDvRVgLHzGGodjUYTERURoVAUF8yKppwUQ8L69YeQ4xCTbJPzf80076"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1761648188.811568,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "sidts-CjEBQT4rX-QX3SOp4iMjZXcNhatzVykRg3mstnl5m6qEjKpIeJS_KgV1dTOVL8ygsBrDEAA"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1730381597,
        "hostOnly": false,
        "httpOnly": false,
        "name": "CONSISTENCY",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AKreu9s2xZyqDcT_zHAERm_tIOhXPW1eTGe7rw_4VRcrK5QZebjVzCb5O1_f1y76MRU9MKrnPcIw0UX3qFuUiJAu2tmHZlTR7IibtTzB0r6OuABC0kNjYKpn9kM6zwBsKakUv5qL2vRTzKslNTc0rqUUMMdfbeTdnqy0IgJUfpWKIDc4nMAjZC8oiYn3x2It0vpBlrk7F1UsQ4AEnNYUN1G9_jWBibGwKR0nVFQ9dHslSRcDXuw5Wu1WICjtw3bRZ1osmu2xD6j4p1SVFxLwmFtH6ogCPh5YoO03LrI73r4"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1764845011.277959,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "QI6O5OLsaEnsUY3K/AfUpzSjW4SUhbn4l9"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1761917069.771062,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AKEyXzWy0J90F_DSEsfZuifYhFbLsyheaAEDDg-s5cKYW-BkNqBvnykUA6FnKcbSrUTXpIUDLtU"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1764845011.277838,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AZxPS1PRwpKYyhmlj"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1764845011.278009,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "QI6O5OLsaEnsUY3K/AfUpzSjW4SUhbn4l9"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1764845011.278483,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "g.a000pgifhjfpgxS7CvT5PGgI1X8OePgRoYbEOYFJLaVgu3vR_tZVpYDPPhHhfs6v_tqc6zy6qQACgYKAfUSARUSFQHGX2MihUofZpDPimAGXE-GWLMOFBoVAUF8yKptq089vH2JdWwWE-UFlf4g0076"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1764845011.278101,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "QI6O5OLsaEnsUY3K/AfUpzSjW4SUhbn4l9"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1761917069.771179,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AKEyXzX-cTfUoAx6pWsbxZSSrWSlml7EFVYRgOmNEkgVka0m6RbHGWghIL5MOxskYL4orq_GYok"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1761648188.811776,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "sidts-CjEBQT4rX-QX3SOp4iMjZXcNhatzVykRg3mstnl5m6qEjKpIeJS_KgV1dTOVL8ygsBrDEAA"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1760969484.582328,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GA1.1.911662981.1726409147"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1760969502.791636,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_VCGEPY40VB",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GS1.1.1726409146.1.1.1726409502.40.0.0"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1764845011.277903,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "iXZ2yVsqVt5R0uju/AMGx0grtk5XdhXtFW"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1764845011.277708,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "AbQRY9cHopLQNeTX9"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1764335597.957433,
        "hostOnly": false,
        "httpOnly": true,
        "name": "LOGIN_INFO",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AFmmF2swRgIhAPXEN9u2BHveiFaM1Xo-7Hoi3xT3i7s8KqfRIzOfx1NZAiEAj99M9f_PeI9c6PoTyKH0Dmmq_eX4J3UZEbV26bkG4Bs:QUQ3MjNmeER3QlRyRG9ZRGJaZXY1dDBmakppeEFFMTJlQ3hVVlBMRXp1d2lvT1h4TktaanpLdlZUa1ExRlIwY1AxbDV3Zjg5SElNSDRJSHhTaExJLTdERlNacUxjczhIVHB2TnhIV2xzbDV1VVZ3R1NxMXM4UjhWMFVuY0tVQjhUVmN0QVZ1Mk96WmlRWWQ1eEt3MjZVX0dnYjA3bG40cjZn"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1742220350.498699,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "517=Fh_gRvLRWb6u9vNJXcPUJkoi2w4gN4noeXRr_fHeE7dLeCHMnU7ZSHgfAXwnsJyPAXv93fiL6t3raFhkdl5_kApni4n_MWu5NL_JYc8JS7-v8p40d1HycNFk3UwWW94s5A-g6MWDjdBA-aKqeZBTilwbtWr0g0QDO7agFnw2dlx-X-JDGChO_ei-m61Aji8BtFYHY5HKsU8sc0rdQYA9N2O2JKKUFl5CbcmteStsRnfTj8baPw"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1764941051.352034,
        "hostOnly": false,
        "httpOnly": false,
        "name": "PREF",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "volume=38&f6=40000080&f7=100&tz=Asia.Karachi&repeat=NONE&autoplay=true"
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1743928479.863218,
        "hostOnly": false,
        "httpOnly": true,
        "name": "VISITOR_INFO1_LIVE",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "FhBbJkSDphg"
    }
]